### ISSUE TITLE
random fanart not available for movie/tvshows

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#10]
with the latest update .5? i think - noticed artwork was not displaying for tile image and doesnt seem available for choice as widget either.

![2015-09-12_01-44-04](https://cloud.githubusercontent.com/assets/6510026/9830778/39c8c47c-58f0-11e5-87f8-ca1080a244b2.png)

**Comment by marcelveldt** [comment]
Should now be fixed

**Comment by mgonzales71** [comment]
thanks - did you already commit the fix to the helper service?  I just tried the git copy - still seeing the issue.

**Comment by mgonzales71** [comment]
also startup for skin is no longer being displayed - helper issue or skin issue?

**Comment by mgonzales71** [comment]
reverting back to https://github.com/marcelveldt/script.skin.helper.service/blob/1d7d54e79a01ceba32f9825d58d3c0e17d45b569/resources/lib/BackgroundsUpdater.py
restores the fanart for tile images on home.

**Comment by marcelveldt** [comment]
Ok, thanks. I just took a quick peek at it but apparently the code isn't fixed. I'm in belgium now so won't be able to fix it until tomorrow.

**Comment by marcelveldt** [comment]
It's now fixed..
