### ISSUE TITLE
PVR channels widget doesn't work anymore

### ISSUE THREAD

**Issue by mac1202** [marcelveldt/script.skin.helper.service#66]
Hi I use latest krypton from git and mimic skin. If I correctly understand the widget part is managed by your addon. The problem I had is with recent git version of krypton the PVR channel widget stop working it just display nothing. The strange thing is the PVR channel with artwork widget is working perfectly.

**Comment by marcelveldt** [comment]
This should be fixed in the current beta version of this script. It will be available on the Kodi repo as soon as skinners had the time to adopt the changes in their skins.

**Comment by mac1202** [comment]
Unfortunately still broken with the latest version (1.0.120) of your beta repo and the latest git version of mimic18 that adopt the new change of skin helper service.
Here the only error line I found in my log that seems related 
`DEBUG: Skin Helper ArtUtils --> Error in <bound method Pvr.process_channel of <pvr.Pvr object at 0x7f7a264ab1d0>>`

**Comment by marcelveldt** [comment]
Sorry, there was another error in there. I will provide a new beta version on my repo within an hour.

**Comment by mac1202** [comment]
1.0.121 fixed the issue. But in old version of your addon there was two version of the channel pvr widget with and without artwork. In the new release there is only one the one that display artwork, are you planning to reintroduce the version without artwork ?
One more thing, don"t kow if it s skin related or a problem from skin helper.  But the EPG info displayed by the widget are only refreshed the first time the widget is displayed, this should be refreshed everytime.
Edit : after a little bit more testing it seems to work very randomly sometime the widget is displayed sometime it isnt.

**Comment by mac1202** [comment]
I close this one as for now the widget is always showed, and open a new one for the epg info that is not refreshed.
